# config/packages/serializer.yaml

framework:
  serializer:
    enabled: true
    #enable_annotations: true
    default_context:
      default_output_format: json
    #groups: [ 'serialization' ]
    mapping:
      paths: [ '%kernel.project_dir%/config/serializer' ]